jacc/awesome-discord

- readme.md
Hey jack, it's nice to see you again :)
I've added a few things. Hope you come back to Discord soon (if you can, at least)
> libs: add python libs, fix some stuff

- readme.md
I reformatted all of the languages and finally added them. I also added some popular Reddit servers.
> lots of changes

- readme.md
> Added DiscordEmoji.com

- readme.md
> Add Nadeko

- readme.md
**Website -** bot.discord.io
**Guild -** /MNaeSzN
------
Created a custom category "Custom Bot Invites".
> Added bot.discord.io to the Community list.

- readme.md
Website - **blargbot.xyz**
Server - **/QDZYgEq**
> Added "Blargbot" to the list of Bots.

- readme.md
**Changelog**
Added a "Subreddits" category.
Added a custom icon-badge instead of emoji.
Filled the category with a few subreddits (discord_bots; discordservers; discordapp). 
**Suggested Guidelines**
- Must be directly related to discordapp.
- Must have an active Moderation Team.
- Must have at least 1 000 subscribers.
> Added a "Subreddits" category.

- readme.md
**Organization:** https://github.com/DiscordInjections
**Repository:** https://github.com/DiscordInjections/DiscordInjections
-----
**Repository:** https://github.com/justinoboyle/mydiscord
-----
**Organization:** https://github.com/DiscordForge
**Repository:** https://github.com/DiscordForge/DiscordForge
**Website:** https://discordforge.me/
> Add "DiscordInjections" & "MyDiscord" to the Addons category.

- readme.md
This request answers the "Back To Tops" card in the project "Future".
> Added "Back To Tops" buttons.

- readme.md
**From** - To get here, go to [...]
**To** - To get here, simply visit [...]
> Improved phrasing for the headlines.

- readme.md
Website: https://hex.pm/packages/discord_alchemy
This pull request fixes #11 - (Required by OvermindDL1)
> Added Discord_Alchemy to the libraries

- readme.md
- Community Programs 
- [Hypesquad](https://discordapp.com/hypesquad) 
- [Partners](https://discordapp.com/partners)
- [Verification](https://discordapp.com/verification)
> Added Community Programs under Official Resources

- readme.md
> Added missing BTP buttons.

- readme.md
**Organization:** https://github.com/DiscordForge
**Repository:** https://github.com/DiscordForge/DiscordForge
**Website:** https://discordforge.me/
> Add DiscordForge to Addons

- readme.md
**Github** - https://github.com/tscs37/discord.mods
**Gitlab** - https://gitlab.com/tscs37/d.mods
> Added Discord.Mods to "Addons"

- readme.md
I'd really rather you asked next time...
> Remove memework from server list

- readme.md
Added a lil' `;` between the libraries. Looks.. better?
> Updated "Programming Libraries"

- readme.md
Also you might want to remove the libraries cuz discord has an official list for that
> Adding a new "Community Resources" section with 3 links

- readme.md
Hey there; this commit is just a way to showcase the changes suggested in #15.
> Delete the "Popular Servers" category. See desc.

- readme.md
> Add Tweetcord to list of awesome bots

- readme.md
> add lolbot

- readme.md
- Separate Mods and Addons, as Addons are allowed and Mods aren't
- Change SimplePresence description to highlight music rich presence
*Note: I created SimplePresence, that's why I think it'd be best to separate Mods and Addons, so that people don't get confused.*
> Separate Mods and Addons, Update Descriptions

- code-of-conduct.md
- contributing.md
- readme.md
- Start descriptions with capital letter
- End descriptions with period
- Change URLS to Links
- Remove Discord Nitro as it doesn't fit with rest of Links
- Use Sindre's awesome-nodejs as a template
- Adapt template for awesome-discord
- Use Contributor Covenant Template
- Request contact on Discord
> Improve awesome-discord to align with Sindre's requests

- readme.md
> #41 - Add descriptions for all official resources

- readme.md
- **Greatly improve Community/Official Resources formatting**
- Move Subreddits above the Resources
- Move Official Resources above Community Resources
- Put guides into Community Resources
- Change "Developer Tutorials" to "Guides and Tutorials"
- Other minor formatting changes
> Improve Community Resources and ordering

- readme.md
I fixed 2 server invite links that were outdated,
Added Discord Bot lists although maybe you should put those in the Bots section
Added the permissions calculator
Also, if you want you can include [this](https://github.com/Gamerein/rooCollection) collection of roo emojis to the Emojis section but I decided not to include it in the pr
> Small additions

- readme.md
blargbot should not be capitalized.
> uncapitalize blargbot

- readme.md
Added https://discordsl.com server list
> Add discordsl.com

- readme.md
Frictionless integration between Google Drive and Discord, as a service.
Written in golang
https://github.com/RISE-Project-STI2D/gdrive2discord
> Added a new tool named gdrive2discord

- readme.md
* Added nyxx to Dart libs
* Added Haxe lib
* Added Discord Server List to server list
* Updated Discord bot lists
* Added information about the different types of Nitro
* Added warning about using client mods
* Added Powercord client mod
* Fixed grammar mistake in Emoji
* Removed dead bots
* Updated bot and lib URLs
* Fix spacing
> Update a lot of stuff

- readme.md
also add the `/rpc` list of discordapps.dev
i think we're awesome cus we're open source
> Rename ls.terminal.ink to discordapps.dev

- readme.md
http://nntin.github.io/discord-logo
This project allows you to customize your own animated discord logo. It supports 5 unique animations, any color combination, 4 "eyes" styles and the ability between choosing "corner", standard and "speech bubble".  
At the end you get the corresponding HTML and CSS code needed for your website.
> Added discord-logo

- readme.md
The site no longer responds. In other words, it is not working anymore.
> Remove automacord

- readme.md
Changelog:
1. Alphabetically list everything (instead of random, prevents biased listing)
2. Remove deprecated and duplicated entries
3. Grammar/spelling fixes
> Various Changes

- readme.md
This is a bit different to SimplePresence as it comes with a default MultiRPC profile with images and with a custom designed interface you can easily add multiple custom profiles to create and load your own rpc apps.
> Add MultiRPC an easy to use custom rich presence app

- readme.md
Add disforge.com servers and bots
> Add disforge.com servers and bots

- readme.md
Hi !
I recomend adding the tscord template.
[tscord](https://github.com/barthofu/tscord) is a template meant to allow people to deploy a full-fletched discord.js bot in minutes.
It helped me a lot when deploying fast/meme bots as well as complete ones. Feel free to look into it.
> Add the tscord discord.js template

- readme.md
Site has been compromised and links to a xxx website instead, now.
> Removed Topbotlist

- readme.md
[durl](https://github.com/lukepighetti/durl) is a curl-like command line client for Discord API that handles authentication. It was inspired by [twurl](https://github.com/twitter/twurl)
> Add durl to tools

- readme.md
This adds the popular interactions.js library used to create HTTP-only bots for discord.
> feat(apis): add interactions.js
